### PR TITLE
Add some inspiration and material motion api guideline

### PR DESCRIPTION
**Pull request by josephrexme**

### CODE REVIEW

**Comment by fliptheweb** [comment]
Thank you for pull request! Sorry for long reply.
1. You missed dots on the end of the items, but i'll fix it anyway, cuz will make small reformat of my list soon.
2. Not sure about `https://material-motion.github.io/material-motion/`, don't find any demos on the page. And the "Guidelines" section about public motion design guidelines of companies/OS, not about tools or libraries. Maybe there is a nice idea to add some description about that in the beginning of the section.

**Comment by josephrexme** [comment]
Oh thanks @fliptheweb . I have some more things to add to the list and I'm sorry I didn't pay attention to the periods at the end of each list. And I agree with you abutter material-motion. Looks like it doesn't fit in that section so I'd just take it out in my next commit

**Comment by fliptheweb** [comment]
@bl4ckdu5t thank you for helping!

**Comment by fliptheweb** [comment]
Sorry about that, but i closed that pr, the very long time passed :)

**Pull request closed without merging**
